export const PARAM_GETFUND = {
  top: 10,
  skip: 0,
  filters: "{}",
  showHistoricData: false,
  displayFundsByCategories: "False",
  countries: '["R0JS"]',
  countryIds: '["ezk4NjFBMjQ2LTU5NzQtNDU0Ny05MUFGLUY3QkNBNUEzNTUzRH0="]',
  fundRanges:
    '["Aberdeen Standard Unit Trust I","Aberdeen Standard SICAV I","Aberdeen Standard OEIC VII","Aberdeen Standard OEIC I","Aberdeen Standard OEIC II","Aberdeen Standard OEIC III","Aberdeen Standard OEIC VI","Aberdeen Standard OEIC V","Aberdeen Standard OEIC IV","Aberdeen Standard Islamic SICAV","Aberdeen Life Funds","Aberdeen Property ICVC","Aberdeen Property Unit Trust","Aberdeen Standard Liquidity Fund (Lux)","Strategic Active Trading Fund Plc","Standard Life Investments Global SICAV","Standard Life Investments Global SICAV II","SLTM Limited Unit Trusts","UK Unit Trust (SLI)","Standard Life Investments UK Real Estate Funds ICVC","Standard Life Investments UK Real Estate Trust"]',
  fundRangeIds:
    '["e0JBRTBBRjZBLUU2MTktNDE2My1CMkYxLTZCNUM2MUZGQkFGM30=","ezVCQ0ZDRjkxLTQ2RUUtNEI1OS05ODAxLUY3RjhFMkFCMjc3MX0=","e0Q5NUE5OTVCLTlBNzUtNDJFQi1BREYxLTZCNzk3NDY3OEY4Q30=","e0ZCODc2NEIxLTFENzYtNDY5My05REY2LTg5RDg0MTY2ODg1RH0=","e0VBRkNGM0I1LUZEQjktNDBDQS05QUM0LTZBOTNEN0E2RDEwMX0=","e0IzMkVERDA4LUIyOTEtNEJFMi1BRjUwLTYxQjVFMzNBOTkzQX0=","ezcyNkJFN0VDLTU5NTktNEJBRS1BQTYyLThDMjhFRjFEQTNENn0=","e0Q4OUYxNjYwLUEwODgtNEU0Qi1BQjA2LTc2RENCQUM1MzI1QX0=","ezc0OTM0Nzc4LUQwMkItNDdFMy1CRTFELTU3QjE2Qzc5QjE3NX0=","ezc1OUEwQjRELUVDRDktNEFDNy04M0E3LUQ0RUZBOTBCRTVFNX0=","ezIxMDgxM0Y3LUM0RUEtNEE4MS05NjJELTdGMDU0QkMyRkZFOX0=","ezdCM0RFMzMzLTMwRTgtNERCNi05QTU0LTFCNkVGQkJDNDIwQn0=","ezdEMjFFNTI5LUI0MUUtNDk1MC1CNTI4LTkwRTFBMUFBM0NDN30=","ezBGNjZEMkU2LTYzMzgtNDAyQS1BQUU5LUZCNzBGMzgzMDhCRH0=","ezJBOEIxMjc0LUNDNkMtNDdDOS04QzU4LTJCRThCMUVDQzJDRX0=","e0E3QTUzNzQxLTJEQzItNDA0Qi1CODEzLUY4OUVBNThENEEyNX0=","ezgxRDEzRkY0LUEzRjAtNEY1RC1CQjlFLUYyQjhBODRCMzM4RX0=","ezQ0QzhGMDk2LUNGNTEtNDJCRS1CNDRDLTQyQTBCRThFOTEwMH0=","ezIwQTBCNzZCLUUzRTUtNEY4OC05QkI4LTVEQTYxMjM4QUJDRX0=","e0FFNEJDRUI3LUEzRkItNEUwRi1CNkI4LTRCN0MwOTNEM0MxQ30=","ezkxREY2MUYxLUYwNDAtNDE4RS05QTIxLTM0RkE2MTk5OEE2QX0="]',
  investorTypes: '["4","3","1"]',
  investorTypeIds:
    '["e0JGN0MwMURELUU0N0QtNDI2OC05MUQ1LURBQUE3QjBCMUU5RH0=","ezdFNzEyRDI2LThBNDgtNDQ3Ri1CMEIxLUI0RkNCRjIxNzc4NH0=","e0QyN0E1REYzLTJGNjktNEJFRC05NkFGLTkwNkUxOThDQjI3RX0="]',
  footnoteTypesIds: "[]"
};
export const PARAM_GETFUND1 = {
  top: 10,
  skip: 0,
  filters: {},
  showHistoricData: false,
  displayFundsByCategories: false,
  countries: ["R0JS"],
  countryIds: ["ezk4NjFBMjQ2LTU5NzQtNDU0Ny05MUFGLUY3QkNBNUEzNTUzRH0="],
  fundRanges: [
    "Aberdeen Standard Unit Trust I",
    "Aberdeen Standard SICAV I",
    "Aberdeen Standard OEIC VII",
    "Aberdeen Standard OEIC I",
    "Aberdeen Standard OEIC II",
    "Aberdeen Standard OEIC III",
    "Aberdeen Standard OEIC VI",
    "Aberdeen Standard OEIC V",
    "Aberdeen Standard OEIC IV",
    "Aberdeen Standard Islamic SICAV",
    "Aberdeen Life Funds",
    "Aberdeen Property ICVC",
    "Aberdeen Property Unit Trust",
    "Aberdeen Standard Liquidity Fund (Lux)",
    "Strategic Active Trading Fund Plc",
    "Standard Life Investments Global SICAV",
    "Standard Life Investments Global SICAV II",
    "SLTM Limited Unit Trusts",
    "UK Unit Trust (SLI)",
    "Standard Life Investments UK Real Estate Funds ICVC",
    "Standard Life Investments UK Real Estate Trust"
  ],
  fundRangeIds: [
    "e0JBRTBBRjZBLUU2MTktNDE2My1CMkYxLTZCNUM2MUZGQkFGM30=",
    "ezVCQ0ZDRjkxLTQ2RUUtNEI1OS05ODAxLUY3RjhFMkFCMjc3MX0=",
    "e0Q5NUE5OTVCLTlBNzUtNDJFQi1BREYxLTZCNzk3NDY3OEY4Q30=",
    "e0ZCODc2NEIxLTFENzYtNDY5My05REY2LTg5RDg0MTY2ODg1RH0=",
    "e0VBRkNGM0I1LUZEQjktNDBDQS05QUM0LTZBOTNEN0E2RDEwMX0=",
    "e0IzMkVERDA4LUIyOTEtNEJFMi1BRjUwLTYxQjVFMzNBOTkzQX0=",
    "ezcyNkJFN0VDLTU5NTktNEJBRS1BQTYyLThDMjhFRjFEQTNENn0=",
    "e0Q4OUYxNjYwLUEwODgtNEU0Qi1BQjA2LTc2RENCQUM1MzI1QX0=",
    "ezc0OTM0Nzc4LUQwMkItNDdFMy1CRTFELTU3QjE2Qzc5QjE3NX0=",
    "ezc1OUEwQjRELUVDRDktNEFDNy04M0E3LUQ0RUZBOTBCRTVFNX0=",
    "ezIxMDgxM0Y3LUM0RUEtNEE4MS05NjJELTdGMDU0QkMyRkZFOX0=",
    "ezdCM0RFMzMzLTMwRTgtNERCNi05QTU0LTFCNkVGQkJDNDIwQn0=",
    "ezdEMjFFNTI5LUI0MUUtNDk1MC1CNTI4LTkwRTFBMUFBM0NDN30=",
    "ezBGNjZEMkU2LTYzMzgtNDAyQS1BQUU5LUZCNzBGMzgzMDhCRH0=",
    "ezJBOEIxMjc0LUNDNkMtNDdDOS04QzU4LTJCRThCMUVDQzJDRX0=",
    "e0E3QTUzNzQxLTJEQzItNDA0Qi1CODEzLUY4OUVBNThENEEyNX0=",
    "ezgxRDEzRkY0LUEzRjAtNEY1RC1CQjlFLUYyQjhBODRCMzM4RX0=",
    "ezQ0QzhGMDk2LUNGNTEtNDJCRS1CNDRDLTQyQTBCRThFOTEwMH0=",
    "ezIwQTBCNzZCLUUzRTUtNEY4OC05QkI4LTVEQTYxMjM4QUJDRX0=",
    "e0FFNEJDRUI3LUEzRkItNEUwRi1CNkI4LTRCN0MwOTNEM0MxQ30=",
    "ezkxREY2MUYxLUYwNDAtNDE4RS05QTIxLTM0RkE2MTk5OEE2QX0="
  ],
  investorTypes: ["4", "3", "1"],
  investorTypeIds: [
    "e0JGN0MwMURELUU0N0QtNDI2OC05MUQ1LURBQUE3QjBCMUU5RH0=",
    "ezdFNzEyRDI2LThBNDgtNDQ3Ri1CMEIxLUI0RkNCRjIxNzc4NH0=",
    "e0QyN0E1REYzLTJGNjktNEJFRC05NkFGLTkwNkUxOThDQjI3RX0="
  ],
  footnoteTypesIds: []
};

export const PARAM_FUNDDETAILS = {
  FundCentreAccordionColumns: [
    {
      isMyFunds: true,
      Id: "myFunds",
      DisplayName: "My Funds",
      ApiFieldName: "MyFunds",
      Tooltip: ""
    },
    {
      Id: "e0Q2NDg2MTVGLTIzQjgtNENBOC05QjAzLTlGOEQ5MzM2RUExQn0=",
      DisplayName: "Shareclass",
      Tooltip: "",
      ApiExpandFieldName: "",
      ApiFieldName: "Name",
      ApiCurrencyFieldName: "",
      ApiDateFieldName: "",
      StrippedStrings: "",
      UseRedGreenArrows: "",
      IsCollection: false,
      NeedsNumberFormatting: false,
      DecimalPlaces: 2,
      NeedsLocalisedNumberFormatting: false,
      NeedsCompactCurrencyFormatting: false,
      CustomDateFormat: "",
      NeedsNumberCurrency: false,
      IsPercentage: false,
      DataColumnProvider: "",
      DataColumnProviderName: null,
      DataColumnProviderBaseTemplateId: null,
      IsCustomColumn: false
    },
    {
      Id: "e0M4MTMyRDRCLTM1NDctNDNERS04QzkyLTM0NEQ1MDE0RDlBQ30=",
      DisplayName: "Currency",
      Tooltip: "",
      ApiExpandFieldName: "",
      ApiFieldName: "ShareclassCurrencyCode",
      ApiCurrencyFieldName: "",
      ApiDateFieldName: "",
      StrippedStrings: "",
      UseRedGreenArrows: "",
      IsCollection: false,
      NeedsNumberFormatting: false,
      DecimalPlaces: 2,
      NeedsLocalisedNumberFormatting: false,
      NeedsCompactCurrencyFormatting: false,
      CustomDateFormat: "",
      NeedsNumberCurrency: false,
      IsPercentage: false,
      DataColumnProvider: "",
      DataColumnProviderName: null,
      DataColumnProviderBaseTemplateId: null,
      IsCustomColumn: false
    },
    {
      Id: "ezU4QUJCOEU0LTkyQUQtNDY5Ri1BNjBGLURGNUQyMjc1M0FEMX0=",
      DisplayName: "Price",
      Tooltip: "",
      ApiExpandFieldName: "Prices",
      ApiFieldName: "PricePerUnit",
      ApiCurrencyFieldName: "",
      ApiDateFieldName: "Date",
      StrippedStrings: "",
      UseRedGreenArrows: "",
      IsCollection: false,
      NeedsNumberFormatting: true,
      DecimalPlaces: 2,
      NeedsLocalisedNumberFormatting: true,
      NeedsCompactCurrencyFormatting: false,
      CustomDateFormat: "",
      NeedsNumberCurrency: false,
      IsPercentage: false,
      DataColumnProvider: "",
      DataColumnProviderName: null,
      DataColumnProviderBaseTemplateId: null,
      IsCustomColumn: false
    },
    {
      Id: "e0NBNkQxQTJCLUNFODctNDMyQS1CN0Y1LUYyQjVCNzMzMDI0M30=",
      DisplayName: "Price Change",
      Tooltip: "",
      ApiExpandFieldName: "Prices",
      ApiFieldName: "ChangeValue",
      ApiCurrencyFieldName: "",
      ApiDateFieldName: "Date",
      StrippedStrings: "",
      UseRedGreenArrows: "",
      IsCollection: false,
      NeedsNumberFormatting: true,
      DecimalPlaces: 2,
      NeedsLocalisedNumberFormatting: false,
      NeedsCompactCurrencyFormatting: false,
      CustomDateFormat: "",
      NeedsNumberCurrency: false,
      IsPercentage: false,
      DataColumnProvider: "",
      DataColumnProviderName: null,
      DataColumnProviderBaseTemplateId: null,
      IsCustomColumn: false
    },
    {
      Id: "ezdGRjU4RDEzLTE2NzctNDE0Mi04MEJGLUREMjQ0MDA4NTkzOX0=",
      DisplayName: "M2M vs Amortised Cost Diff",
      Tooltip: "",
      ApiExpandFieldName: "",
      ApiFieldName: "LVNAV",
      ApiCurrencyFieldName: "",
      ApiDateFieldName: "Date",
      StrippedStrings: "",
      UseRedGreenArrows: "",
      IsCollection: false,
      NeedsNumberFormatting: true,
      DecimalPlaces: 6,
      NeedsLocalisedNumberFormatting: false,
      NeedsCompactCurrencyFormatting: false,
      CustomDateFormat: "",
      NeedsNumberCurrency: false,
      IsPercentage: false,
      DataColumnProvider: "",
      DataColumnProviderName: null,
      DataColumnProviderBaseTemplateId: null,
      IsCustomColumn: false
    },
    {
      Id: "ezgzNzQwRDc1LUJDMTAtNDg2OC1CMDUwLTAzMUZENDg2MzJDMn0=",
      DisplayName: "Price Date",
      Tooltip: "",
      ApiExpandFieldName: "Prices",
      ApiFieldName: "Date",
      ApiCurrencyFieldName: "",
      ApiDateFieldName: "Date",
      StrippedStrings: "",
      UseRedGreenArrows: "",
      IsCollection: false,
      NeedsNumberFormatting: false,
      DecimalPlaces: 2,
      NeedsLocalisedNumberFormatting: false,
      NeedsCompactCurrencyFormatting: false,
      CustomDateFormat: "",
      NeedsNumberCurrency: false,
      IsPercentage: false,
      DataColumnProvider: "",
      DataColumnProviderName: null,
      DataColumnProviderBaseTemplateId: null,
      IsCustomColumn: false
    }
  ],
  PriceDate: "",
  LanguageCode: "en",
  DateFormat: "dd MMM yyyy",
  CspUris: [
    "https://api.aberdeenstandard.net/portfolio/shareclasses/27fbf606-0209-38e0-6078-ad902dbb6184",
    "https://api.aberdeenstandard.net/portfolio/shareclasses/e6b980a9-eea0-f9f0-fc99-8e95e0b568d0",
    "https://api.aberdeenstandard.net/portfolio/shareclasses/cb02736f-ccd0-2f08-2a76-83cc4d65f6f9",
    "https://api.aberdeenstandard.net/portfolio/shareclasses/bc1b1db6-7511-7a40-88f0-0866d93dccf1",
    "https://api.aberdeenstandard.net/portfolio/shareclasses/7fae3a81-c0d8-db60-ff43-f2fd7b1816a6"
  ],
  FundId: "08d7cf15-a530-d2c4-41a0-a972b234f96e",
  FundName: "Aberdeen Standard Liquidity Fund (Lux) - Sterling Fund",
  FundRangeId: "NDBjYTQyNTQtZjkzNS1kNTIyLWY0YzYtZWFkN2Y0ZjBlNWFh",
  Countries: ["ezk4NjFBMjQ2LTU5NzQtNDU0Ny05MUFGLUY3QkNBNUEzNTUzRH0="],
  CountryNames: ["UNITED KINGDOM"],
  CountryCodes: ["R0JS"],
  InvestorTypes: [
    "e0JGN0MwMURELUU0N0QtNDI2OC05MUQ1LURBQUE3QjBCMUU5RH0=",
    "ezdFNzEyRDI2LThBNDgtNDQ3Ri1CMEIxLUI0RkNCRjIxNzc4NH0=",
    "e0QyN0E1REYzLTJGNjktNEJFRC05NkFGLTkwNkUxOThDQjI3RX0="
  ],
  InvestorCodes: ["4", "3", "1"],
  DocumentInvestorTypes: [
    "f4f425111dfa4a0cbcad66f158e403be",
    "84d15c7cb7714379b26fab16abd13870",
    "c0d71aa427144d1a9dc2e7336921d88c"
  ],
  EnableInternalFundPageLinks: true,
  FootnoteTypesIds: [],
  ShowHistoricData: false
};
